/**
 * @module Bcrypt password utility
 * @module JsonWebToken tokken utility
 */
const bcrypt = require("bcrypt");
const jsonWebToken = require("jsonwebtoken");

/**
 * @import Moongose shema User
 */
const User = require("../models/user");

/**
 * Creation of a new User object with encrypted password
 * @param {*} request
 * @param {*} response
 * @param {*} next
 */
exports.signup = (request, response, next) => {
	bcrypt
		.hash(request.body.password, 10)
		.then((hash) => {
			const user = new User({
				email: request.body.email,
				password: hash,
			});
			user
				.save()
				.then(() =>
					response.status(201).json({ message: "Utilisateur créé !" })
				)
				.catch((error) => response.status(400).json({ error }));
		})
		.catch((error) => response.status(500).json({ error }));
};

/**
 * Search user in database with the email as the identifier.
 * If the user is found bcrypt compare the entered password with the database.
 * If the password is correct returns response whith status 200
 * as well as the id generated by mongodb and a unique tokken.
 * @param {*} request
 * @param {*} response
 * @param {*} next
 */
exports.login = (request, response, next) => {
	User.findOne({ email: request.body.email })
		.then((user) => {
			if (!user) {
				return response.status(401).json({
					error: "Email introuvable !",
				});
			}
			bcrypt
				.compare(request.body.password, user.password)
				.then((valid) => {
					if (!valid) {
						return response.status(401).json({
							error: "Mot de passe incorrect !",
						});
					}
					response.status(200).json({
						userId: user._id,
						token: jsonWebToken.sign(
							{
								userId: user.id,
							},
							"RANDOM_SECRET_KEY",
							{ expiresIn: "24h" }
						),
					});
				})
				.catch((error) => response.status(500).json({ error }));
		})
		.catch((error) => response.status(500).json({ error }));
};
